export const USER_LOGIN_SUCCESS="USER_LOGIN_SUCCESS";
export const USER_SIGNUP_SUCCESS ="USER_SIGNUP_SUCCESS";


export const USER_LOGIN_ERROR="USER_LOGIN_ERROR";
export const USER_SIGNUP_ERROR ="USER_SIGNUP_ERROR";


export const APP_LOADING ="APP_LOADING";
export const APP_NOT_LOADING ="APP_NOT_LOADING";


//PASSWORDS

export const GET_USER_PASSWORDS_SUCCESS ="GET_USER_PASSWORDS_SUCCESS";
export const GET_USER_PASSWORDS_ERROR ="GET_USER_PASSWORDS_ERROR";
export const ADD_PASSWORD_SUCCESS="ADD_PASSWORD_SUCCESS";
export const ADD_PASSWORD_ERROR="ADD_PASSWORD_ERROR";
export const DELETE_PASSWORD_SUCCESS="DELETE_PASSWORD_SUCCESS";
export const DELETE_PASSWORD_ERROR ="DELETE_PASSWORD_ERROR";
export const EDIT_PASSWORD_SUCCESS="EDIT_PASSWORD_SUCCESS";
export const EDIT_PASSWORD_ERROR ="EDIT_PASSWORD_ERROR";



//SERVER 
export const SERVER_ERROR_OCCUR ="SERVER_ERROR_OCCUR";
export const SERVER_ERROR_RESTART ="SERVER_ERROR_RESTART";